"""changing more objects in model to not nullable

Revision ID: 77d821177213
Revises: 65ccff575464
Create Date: 2021-02-25 15:51:10.852145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d821177213'
down_revision = '65ccff575464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'past_shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Venue', 'upcoming_shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'upcoming_shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Venue', 'upcoming_shows',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'past_shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Venue', 'past_shows',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Artist', 'upcoming_shows',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Artist', 'past_shows',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
